### ISSUE TITLE
AliWangWang 10.01.03C

### ISSUE THREAD

**Issue by AlektroNik** [KKomarov/AliWangWangEng#2]
Добрый день.
Я так понимаю для 10 версии все сильно изменилось.
Максимум нашел папку с локалями AliWangWang\10.01.03C\locales\en-US.pak.
Подскажите, пожалуйста, как можно английскую версию поставить или локализовать?

**Comment by KKomarov** [comment]
Good evening,
I had a look at 10 version and found that language files actually located at AliWangWang\10.01.03C\Resources\Translations\
They are Qt lingust files, you can use Qt lingust to translate them. https://doc.qt.io/qt-6/linguist-translators.html
As a quick solution, you can just delete or rename folder AliWangWang\10.01.03C\Resources\Translations\appts_zh_CN
Then application will use text ids, they are in english
![aliw10](https://user-images.githubusercontent.com/14128194/190273855-0ab6648e-f72d-4298-942e-a74a1ca6f264.JPG)

**Comment by AlektroNik** [comment]
Thank you very much 🤗🍻
